name: spells_and_tools
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.0+11

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # state management
  riverpod: 
  flutter_riverpod: 
  hooks_riverpod:
  flutter_hooks: 
  rxdart:

  # dart
  path: 
  collection: 
  async:

  # html/markdown
  flutter_html:
  flutter_html_table:
  markdown:
  
  # firebase
  firebase_core:
  firebase_auth:
  firebase_ui_auth:
  firebase_ui_localizations:
  firebase_ui_oauth_google:
  firebase_ui_oauth_apple:
  firebase_analytics:
  firebase_remote_config:
  firebase_crashlytics:
  firebase_messaging:
  cloud_firestore: ^5.6.8

  # misc
  url_launcher:
  shared_preferences: 
  uuid: 
  go_router: 
  image_picker: 
  path_provider:
  http:
  flutter_svg: 
  flutter_cache_manager:
  package_info_plus: 
  fast_immutable_collections: 

  # ui
  material_symbols_icons:
  

  # publishing
  flutter_native_splash:
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  test: 
  google_fonts: 

flutter:
  fonts:
    - family: SocialIcons
      fonts:
        - asset: fonts/FontAwesome-SocialIcons.otf
    - family: CrimsonText
      fonts:
        - asset: fonts/CrimsonText-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/CrimsonText-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/CrimsonText-SemiBold.ttf
          style: normal
          weight: 600
        - asset: fonts/CrimsonText-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/CrimsonText-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/CrimsonText-BoldItalic.ttf
          style: italic
          weight: 700
  uses-material-design: true
  assets:
    - assets/
    - assets/images/spells/
    - assets/images/ui/

